services:
  db:
    image: postgres:15-alpine
    container_name: postgres_sistema_escolar
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5433:5432"
    volumes:
      - .:/sql_scripts
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
